[package]
name = "lurk"
version = "0.1.0"
authors = ["porcuquine <porcuquine@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Coming Soon"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bellperson = { version = "0.14", default-features = false }
ff = { version = "0.3.1", package = "fff" }
generic-array = "0.14.4"
itertools = "0.9"
lazy_static = { version = "1.4.0" }
neptune = { version = "^3.0", default-features = false }
rand = "0.7"

[dev-dependencies]
rand_xorshift = "0.2.0"

[features]
default = ["gpu", "pairing"]

gpu = ["bellperson/gpu", "neptune/opencl"]
pairing = ["bellperson/pairing", "neptune/pairing", "bellperson/pairing"]
blst = ["bellperson/blst", "neptune/blst", "bellperson/blst"]
